###
POST http://localhost:3002/api/auth/register
Content-Type: application/json

{
  "username": "nhan",
  "firstName": "Trong",
  "lastName": "Nhan",
  "password": "12345678"
}

###
POST http://localhost:3002/api/auth/login
Content-Type: application/json

{
  "username": "nxhawk",
  "password": "12345678"
}

###
POST http://localhost:3002/api/auth/login
Content-Type: application/json

{
  "username": "nxhawk",
  "password": "12345678"
}

###
GET http://localhost:3002/api/conversations

###
POST http://localhost:3002/api/conversations
Content-Type: application/json

{
  "username": "nhan",
  "message": "Hello, nhan!"
}
###
GET http://localhost:3002/api/friends

###
DELETE http://localhost:3002/api/friends/1/delete

###
PATCH http://localhost:3002/api/friends/requests/4/accept

###
DELETE http://localhost:3002/api/friends/requests/3/cancel

###
GET http://localhost:3002/api/friends/requests

###
POST http://localhost:3002/api/friends/requests
Content-Type: application/json

{
  "username": "nhan"
}
###
PATCH http://localhost:3002/api/users/presence/status
Content-Type: application/json

{
  "statusMessage": "a"
}

###
GET http://localhost:3002/api/auth/status

###
POST http://localhost:3002/api/auth/login

###
GET http://localhost:3002/api/users

###
POST http://localhost:3002/api/auth/logout

###
GET http://localhost:3002/api/users/search?query=nx

###
GET http://localhost:3002/api/users/check?username=nxhawk

###
PATCH http://localhost:3002/api/users/profile