###
POST http://localhost:3002/api/auth/register
Content-Type: application/json

{
  "username": "nxhawk",
  "firstName": "Nguyen",
  "lastName": "Hao",
  "password": "12345678"
}

###
POST http://localhost:3002/api/auth/login
Content-Type: application/json

{
  "username": "nxhawk",
  "password": "12345678"
}

###
POST http://localhost:3002/api/friends/requests
Content-Type: application/json

{
  "username": "admin"
}
###
PATCH http://localhost:3002/api/users/presence/status
Content-Type: application/json

{
  "statusMessage": "a"
}

###
GET http://localhost:3002/api/auth/status

###
POST http://localhost:3002/api/auth/login

###
GET http://localhost:3002/api/users

###
POST http://localhost:3002/api/auth/logout

###
GET http://localhost:3002/api/users/search?query=nx

###
GET http://localhost:3002/api/users/check?username=nxhawk

###
PATCH http://localhost:3002/api/users/profile